### ISSUE TITLE
Question: Any reason for the `spec` nesting?

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#177]
What's the reason we have:

```yaml
kind: source
spec:
  ## Required. name of the plugin to use
  name: "aws" # required
```

And not:

```yaml
kind: source
name: aws
```
