### ISSUE TITLE
Bug(config): Can't use multiple sources in the same sync

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#350]
### Describe the bug

With the following config:

```yml
kind: source
spec:
  name: aws
  version: v4.6.1
  destinations: [postgresql]
  path: cloudquery/aws
---
kind: source
spec:
  name: azure
  version: v1.3.3
  destinations: [postgresql]
  path: cloudquery/azure
---
kind: destination
spec:
  name: postgresql
  version: v1.6.3
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

The CLI errors out with `Error: failed to load spec(s) from <path>. Error: destination postgresql is used by multiple sources cloudquery/azure with different versions`

### Expected Behavior

Using multiple sources should work

### Steps to Reproduce

Create a YAML file with the above configuration, run `cloudquery sync <file>`

### Possible Solution

Fix the config validation

### Provider and CloudQuery version

v1.5.5
