### ISSUE TITLE
Bug(config-windows): Putting multiple configurations in the same file doesn't work on Windows

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#351]
### Describe the bug

The following config:

```yml
kind: source
spec:
  name: aws
  version: v3.8.0
  destinations: [test,csv]
  path: cloudquery/aws
---
kind: destination
spec:
  name: test
  version: v1.2.11
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
---
kind: destination
spec:
  name: csv
  version: v1.0.0
  write_mode: append
```

Fails on Windows with the following error `Error: expecting at least one destination`

### Expected Behavior

The above config should work on Windows

### Steps to Reproduce

Run a sync on a Windows machine with the supplied configuration

### Possible Solution

Probably related to how we split strings in https://github.com/cloudquery/plugin-sdk/blob/6f27251c9105014160b10c5e08835b8c2ce1fcf6/specs/spec_reader.go#L23

### Provider and CloudQuery version

v1.5.5
