### ISSUE TITLE
Discussion: What is the correct way to reference a community plugin via spec

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#655]
With https://github.com/cloudquery/plugin-sdk/pull/632 I expected the following spec to work for a plugin that is hosted on the repo https://github.com/cloudquery/cq-source-plaid

```yaml
kind: source
spec:
  name: plaid
  version: v1.0.0
  destinations: [postgresql]
  path: cloudquery/cq-source-plaid
  spec:
    client_id: ${PLAID_CLIENT_ID}
    secret: ${PLAID_SECRET}
    access_token: ${PLAID_ACCESS_TOKEN}
```

However it doesn't and only the following works:

```yaml
kind: source
spec:
  name: plaid
  version: v1.0.0
  destinations: [postgresql]
  path: cloudquery/plaid
  spec:
    client_id: ${PLAID_CLIENT_ID}
    secret: ${PLAID_SECRET}
    access_token: ${PLAID_ACCESS_TOKEN}
```

This is not an issue with said PR, but just how the current code expected to work, see tests:
https://github.com/cloudquery/plugin-sdk/blob/384b195ef5abeae6ffeeda9583893b6b2192e23c/clients/source/v0/source_test.go#L23

I find it a bit unintuitive that the path doesn't match the repo.
It this expected or we should make `path: cloudquery/cq-source-plaid` work instead?

> Maybe someone wants to put their plugin under `<org>/my-cq-plugin-repo-test-5`? With the current approach we don't support it. Also it's harder for users to understand where is the plugin hosted
